# Generated by Django 4.2.7 on 2023-12-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
