# Generated by Django 4.2.7 on 2023-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
